-- Create Activity Logs Table (Missing Dependency for verify/submit_prediction)
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    action_type TEXT NOT NULL, -- 'BET', 'RESOLVE', 'FEED_POST', 'POINT_CHANGE'
    asset_symbol TEXT,
    prediction_id BIGINT,
    metadata JSONB, -- Store full context
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Optimization Indexes
CREATE INDEX IF NOT EXISTS idx_activity_logs_user ON activity_logs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_type ON activity_logs(action_type);
