-- ==============================================================================
-- 🚀 VIBE FORECAST: COMPLETE SCHEMA (Consolidated)
-- Includes: Profiles, Predictions (Robust), Feed System (Posts/Interactions), RPCs
-- ==============================================================================

-- 1. Enable Extensions
create extension if not exists pg_net with schema extensions;

-- ==============================================================================
-- 2. PROFILES (User Data)
-- ==============================================================================
create table if not exists public.profiles (
  id uuid not null references auth.users(id) on delete cascade,
  email text,
  username text,
  points integer default 1000 check (points >= 0),
  tier text default 'bronze',
  streak_count int default 0,
  total_earnings numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (id)
);

alter table public.profiles enable row level security;

drop policy if exists "Public profiles are viewable by everyone." on public.profiles;
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
drop policy if exists "Users can insert their own profile." on public.profiles;
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
drop policy if exists "Users can update own profile." on public.profiles;
create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id);

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, username, points)
  values (new.id, new.email, split_part(new.email, '@', 1), 1000)
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ==============================================================================
-- 3. PREDICTIONS (Game Logic)
-- ==============================================================================
drop table if exists public.predictions cascade;

create table public.predictions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  
  -- Info
  asset_symbol text not null,
  timeframe text not null,
  direction text not null check (direction in ('UP', 'DOWN')),
  target_percent numeric not null check (target_percent in (0.5, 1.0, 1.5, 2.0)),
  entry_price numeric not null check (entry_price > 0),
  bet_amount integer not null check (bet_amount > 0), 
  
  -- Status & Result
  status text default 'pending' check (status in ('pending', 'WIN', 'LOSS', 'ND')),
  actual_price numeric,                       
  profit integer default 0,                   
  
  -- Timestamps
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  candle_close_at timestamp with time zone not null, 
  resolved_at timestamp with time zone,
  
  -- Game Comment (Short)
  comment text check (char_length(comment) <= 140) 
);

-- Indexes
create index idx_predictions_status on predictions(status);
create index idx_predictions_user on predictions(user_id);
create index idx_predictions_candle on predictions(asset_symbol, timeframe, candle_close_at);
create index idx_predictions_created on predictions(created_at desc);

-- RLS
alter table public.predictions enable row level security;
drop policy if exists "Predictions are viewable by everyone." on public.predictions;
create policy "Predictions are viewable by everyone." on public.predictions for select using (true);
drop policy if exists "Users can insert their own predictions." on public.predictions;
create policy "Users can insert their own predictions." on public.predictions for insert with check (auth.uid() = user_id);

-- ==============================================================================
-- 4. FEED SYSTEM (Posts, Interactions)
-- ==============================================================================

-- A. Posts Table
create table if not exists posts (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    title text,
    content text,
    
    asset_symbol text,
    timeframe text,
    direction text,
    volatility_target numeric default 0,
    
    likes_count int default 0,
    comments_count int default 0,
    bookmarks_count int default 0,
    shares_count int default 0,
    
    feed_score int default 0,
    freshness_score int default 0,
    engagement_score int default 0,
    author_score int default 0,
    
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table posts enable row level security;
drop policy if exists "Public posts viewable" on posts;
create policy "Public posts viewable" on posts for select using (true);
drop policy if exists "User posts editable" on posts;
create policy "User posts editable" on posts for all using (auth.uid() = user_id);

create index if not exists idx_posts_feed_score on posts (feed_score desc);

-- B. Interaction Tables
create table if not exists likes (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  post_id bigint references posts(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, post_id)
);

create table if not exists comments (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  post_id bigint references posts(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists bookmarks (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  post_id bigint references posts(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, post_id)
);

-- RLS for Interactions
alter table likes enable row level security;
alter table comments enable row level security;
alter table bookmarks enable row level security;

drop policy if exists "Public likes" on likes;
create policy "Public likes" on likes for select using (true);
drop policy if exists "User likes" on likes;
create policy "User likes" on likes for insert with check (auth.uid() = user_id);
drop policy if exists "User unlink likes" on likes;
create policy "User unlink likes" on likes for delete using (auth.uid() = user_id);

drop policy if exists "Public comments" on comments;
create policy "Public comments" on comments for select using (true);
drop policy if exists "User comments" on comments;
create policy "User comments" on comments for insert with check (auth.uid() = user_id);

drop policy if exists "User bookmarks" on bookmarks;
create policy "User bookmarks" on bookmarks for all using (auth.uid() = user_id);

-- ==============================================================================
-- 5. RPC FUNCTIONS
-- ==============================================================================

-- RPC 1: submit_prediction (Game Entry)
create or replace function public.submit_prediction(
  p_user_id UUID,
  p_asset_symbol TEXT,
  p_timeframe TEXT,
  p_direction TEXT,
  p_target_percent NUMERIC,
  p_entry_price NUMERIC,
  p_bet_amount INTEGER
) RETURNS JSONB AS $$
DECLARE
  v_user_points INTEGER;
  v_prediction_id BIGINT;
  v_interval INTERVAL;
  v_candle_close TIMESTAMP WITH TIME ZONE;
BEGIN
  -- Timeframe Logic
  IF p_timeframe = '1m' THEN v_interval := INTERVAL '1 minute';
  ELSIF p_timeframe = '5m' THEN v_interval := INTERVAL '5 minutes';
  ELSIF p_timeframe = '15m' THEN v_interval := INTERVAL '15 minutes';
  ELSIF p_timeframe = '1h' THEN v_interval := INTERVAL '1 hour';
  ELSIF p_timeframe = '4h' THEN v_interval := INTERVAL '4 hours';
  ELSIF p_timeframe = '1d' THEN v_interval := INTERVAL '1 day';
  ELSE v_interval := INTERVAL '1 hour';
  END IF;

  v_candle_close := date_bin(v_interval, now(), '2000-01-01'::timestamp with time zone) + v_interval;

  SELECT points INTO v_user_points FROM profiles WHERE id = p_user_id FOR UPDATE;
  
  IF v_user_points IS NULL THEN RAISE EXCEPTION 'User profile not found'; END IF;
  IF v_user_points < p_bet_amount THEN RAISE EXCEPTION 'Insufficient points'; END IF;

  UPDATE profiles SET points = points - p_bet_amount WHERE id = p_user_id;

  INSERT INTO predictions (
    user_id, asset_symbol, timeframe, direction, target_percent, 
    entry_price, status, bet_amount, candle_close_at, created_at
  ) VALUES (
    p_user_id, p_asset_symbol, p_timeframe, p_direction, p_target_percent, 
    p_entry_price, 'pending', p_bet_amount, v_candle_close, now()
  ) RETURNING id INTO v_prediction_id;

  RETURN jsonb_build_object('success', true, 'prediction_id', v_prediction_id, 'new_points', v_user_points - p_bet_amount);
END;
$$ LANGUAGE plpgsql;


-- RPC 2: resolve_prediction_advanced (Game Result)
create or replace function public.resolve_prediction_advanced(
    p_id bigint,
    p_close_price numeric
)
returns json
language plpgsql
security definer
as $$
declare
    v_prediction record;
    v_price_change numeric;
    v_price_change_percent numeric;
    v_status text;
    v_payout integer := 0;
begin
    select * into v_prediction from predictions where id = p_id and status = 'pending' for update;
    
    if not found then return json_build_object('success', false, 'error', 'Prediction not found'); end if;
    
    v_price_change := p_close_price - v_prediction.entry_price;
    v_price_change_percent := abs(v_price_change / v_prediction.entry_price * 100);
    
    if v_prediction.direction = 'UP' then
        if v_price_change > 0 and v_price_change_percent >= v_prediction.target_percent then
            v_status := 'WIN';
            v_payout := v_prediction.bet_amount * (v_prediction.target_percent * 2 + 1);
        elsif v_price_change < 0 then
            v_status := 'LOSS';
        else
            v_status := 'ND';
            v_payout := v_prediction.bet_amount;
        end if;
    elsif v_prediction.direction = 'DOWN' then
        if v_price_change < 0 and v_price_change_percent >= v_prediction.target_percent then
            v_status := 'WIN';
            v_payout := v_prediction.bet_amount * (v_prediction.target_percent * 2 + 1);
        elsif v_price_change > 0 then
            v_status := 'LOSS';
        else
            v_status := 'ND';
            v_payout := v_prediction.bet_amount;
        end if;
    end if;
    
    update predictions
    set status = v_status, actual_price = p_close_price, profit = v_payout - v_prediction.bet_amount, resolved_at = now()
    where id = p_id;
    
    if v_payout > 0 then
        update profiles set points = points + v_payout where id = v_prediction.user_id;
    end if;
    
    return json_build_object('success', true, 'status', v_status, 'payout', v_payout);
exception when others then
    return json_build_object('success', false, 'error', SQLERRM);
end;
$$;
