
-- ==========================================================
-- 🔄 100% PRECISION SYNC: DEV TO PRODUCTION
-- ==========================================================
-- This script aligns Development with PROD (abpijrm...) 
-- covering all tables, columns, and RPC signatures.

BEGIN;

-- 1. [TABLES] Restore missing tables found in Audit
CREATE TABLE IF NOT EXISTS public.system_configs (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    description TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    action_type TEXT NOT NULL,
    asset_symbol TEXT,
    prediction_id BIGINT,
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    title TEXT,
    content TEXT,
    asset_symbol TEXT,
    prediction_id BIGINT,
    likes_count INTEGER DEFAULT 0,
    comments_count INTEGER DEFAULT 0,
    bookmarks_count INTEGER DEFAULT 0,
    shares_count INTEGER DEFAULT 0,
    feed_score NUMERIC DEFAULT 0,
    freshness_score NUMERIC DEFAULT 0,
    engagement_score NUMERIC DEFAULT 0,
    author_score NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, post_id)
);

CREATE TABLE IF NOT EXISTS public.bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, post_id)
);

CREATE TABLE IF NOT EXISTS public.shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
    platform TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY,
    points INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. [COLUMNS] Fixed Precision Column Alignment
ALTER TABLE public.predictions 
  ADD COLUMN IF NOT EXISTS close_price NUMERIC,
  ADD COLUMN IF NOT EXISTS profit_loss NUMERIC,
  ADD COLUMN IF NOT EXISTS payout NUMERIC,
  ADD COLUMN IF NOT EXISTS actual_change_percent NUMERIC,
  ADD COLUMN IF NOT EXISTS is_target_hit BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS multipliers JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS entry_offset_seconds INTEGER DEFAULT 0;

ALTER TABLE public.notifications 
  ADD COLUMN IF NOT EXISTS points_change INTEGER DEFAULT 0;

DO $$ 
BEGIN 
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='feedbacks' AND column_name='message') THEN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='feedbacks' AND column_name='content') THEN
      ALTER TABLE public.feedbacks RENAME COLUMN message TO content;
    END IF;
  END IF;
  ALTER TABLE public.feedbacks ADD COLUMN IF NOT EXISTS content TEXT;
END $$;

-- 3. [RPC] Restore Missing Production RPCs (to match Prod Signature)

-- [resolve_prediction_v4]
CREATE OR REPLACE FUNCTION public.resolve_prediction_v4(
    p_id BIGINT,
    p_close_price NUMERIC,
    p_timeframe_multiplier NUMERIC DEFAULT 1.0
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
    v_pred RECORD;
    v_payout NUMERIC := 0;
    v_profit NUMERIC := 0;
    v_status TEXT := 'LOSS';
    v_user_id UUID;
    v_new_points NUMERIC;
BEGIN
    SELECT * INTO v_pred FROM predictions WHERE id = p_id;
    IF NOT FOUND THEN RETURN jsonb_build_object('success', false, 'error', 'Not found'); END IF;
    IF v_pred.status != 'pending' THEN RETURN jsonb_build_object('success', false, 'error', 'Already resolved'); END IF;
    v_user_id := v_pred.user_id;

    IF (v_pred.direction = 'UP' AND p_close_price > v_pred.entry_price) OR
       (v_pred.direction = 'DOWN' AND p_close_price < v_pred.entry_price) THEN
       v_status := 'WIN';
       v_profit := v_pred.bet_amount * 0.8 * p_timeframe_multiplier;
       v_payout := v_pred.bet_amount + v_profit;
    ELSEIF p_close_price = v_pred.entry_price THEN
        v_status := 'REFUND'; v_payout := v_pred.bet_amount; v_profit := 0;
    ELSE
        v_status := 'LOSS'; v_payout := 0; v_profit := -v_pred.bet_amount;
    END IF;

    UPDATE predictions SET status = v_status, close_price = p_close_price, payout = v_payout, profit_loss = v_profit, resolved_at = NOW() WHERE id = p_id;
    UPDATE profiles SET points = points + v_profit, streak = CASE WHEN v_status = 'WIN' THEN streak + 1 WHEN v_status = 'LOSS' THEN 0 ELSE streak END WHERE id = v_user_id RETURNING points INTO v_new_points;

    RETURN jsonb_build_object('success', true, 'status', v_status, 'payout', v_payout, 'new_balance', v_new_points);
END;
$function$;

COMMIT;
