-- Create Activity Logs Table (Missing Dependency for verify/submit_prediction)
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    action_type TEXT NOT NULL, -- 'BET', 'RESOLVE', 'FEED_POST', 'POINT_CHANGE'
    asset_symbol TEXT,
    prediction_id BIGINT,
    metadata JSONB, -- Store full context
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Optimization Indexes
CREATE INDEX IF NOT EXISTS idx_activity_logs_user ON activity_logs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_type ON activity_logs(action_type);

-- 1. DROP ALL POSSIBLE OVERLOADS of submit_prediction
-- This ensures there is NO ambiguity when calling the function.
DO $$ 
DECLARE 
    r RECORD;
BEGIN
    FOR r IN (
        SELECT n.nspname, p.proname, pg_get_function_identity_arguments(p.oid) as args
        FROM pg_proc p
        JOIN pg_namespace n ON p.pronamespace = n.oid
        WHERE p.proname = 'submit_prediction' 
          AND n.nspname = 'public'
    ) LOOP
        EXECUTE 'DROP FUNCTION public.submit_prediction(' || r.args || ')';
    END LOOP;
END $$;

-- 2. CREATE THE UNIFIED VERSION
-- This version handles all current requirements: points deduction, candle alignment, opinions, and channels.
CREATE OR REPLACE FUNCTION public.submit_prediction(
    p_user_id UUID,
    p_asset_symbol TEXT,
    p_timeframe TEXT,
    p_direction TEXT,
    p_target_percent NUMERIC,
    p_entry_price NUMERIC,
    p_bet_amount INTEGER,
    p_is_opinion BOOLEAN DEFAULT FALSE,
    p_channel TEXT DEFAULT 'main'
)
RETURNS SETOF public.predictions
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
    v_candle_duration INTEGER;
    v_round_start TIMESTAMP WITH TIME ZONE;
    v_candle_close TIMESTAMP WITH TIME ZONE;
    v_prediction_id BIGINT;
BEGIN
    -- 1. Validate Points (Only for real bets, not pure opinions if desired, 
    -- but usually opinions still have a bet amount or are just 0 bet)
    IF p_bet_amount > 0 THEN
        IF NOT EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE id = p_user_id AND points >= p_bet_amount
        ) THEN
            RAISE EXCEPTION 'Insufficient points';
        END IF;

        -- Deduct Points
        UPDATE public.profiles 
        SET points = points - p_bet_amount 
        WHERE id = p_user_id;
    END IF;

    -- 2. Calculate Candle Alignment (Backend Alignment for Fairness)
    -- This logic derives the candle_close_at based on the current time and timeframe.
    CASE 
        WHEN p_timeframe ~ '^\d+m$' THEN 
            v_candle_duration := (regexp_replace(p_timeframe, '[^0-9]', '', 'g')::INTEGER) * 60;
        WHEN p_timeframe ~ '^\d+h$' THEN 
            v_candle_duration := (regexp_replace(p_timeframe, '[^0-9]', '', 'g')::INTEGER) * 3600;
        WHEN p_timeframe ~ '^\d+d$' THEN 
            v_candle_duration := (regexp_replace(p_timeframe, '[^0-9]', '', 'g')::INTEGER) * 86400;
        ELSE 
            v_candle_duration := 900; -- Default 15m
    END CASE;

    -- OpenTime = Current Time floored to duration
    v_round_start := to_timestamp(floor(extract(epoch from now()) / v_candle_duration) * v_candle_duration);
    v_candle_close := v_round_start + (v_candle_duration * interval '1 second');

    -- 3. Insert Prediction
    INSERT INTO public.predictions (
        user_id,
        asset_symbol,
        timeframe,
        direction,
        target_percent,
        entry_price,
        bet_amount,
        status,
        is_opinion,
        channel,
        candle_close_at,
        created_at
    )
    VALUES (
        p_user_id,
        p_asset_symbol,
        p_timeframe,
        p_direction,
        p_target_percent,
        p_entry_price,
        p_bet_amount,
        'pending',
        p_is_opinion,
        COALESCE(p_channel, 'main'),
        v_candle_close,
        NOW()
    )
    RETURNING id INTO v_prediction_id;

    -- 4. Audit Log (Optionally, if activity_logs table exists)
    -- INSERT INTO public.activity_logs (user_id, action_type, asset_symbol, prediction_id)
    -- VALUES (p_user_id, 'SUBMIT', p_asset_symbol, v_prediction_id);

    -- 5. Return the created prediction
    RETURN QUERY SELECT * FROM public.predictions WHERE id = v_prediction_id;
END;
$function$;
-- 1. Add missing column if it doesn't exist
ALTER TABLE public.notifications 
ADD COLUMN IF NOT EXISTS points_change INTEGER DEFAULT 0;

-- 2. Update resolve_prediction_advanced to populate points_change
CREATE OR REPLACE FUNCTION public.resolve_prediction_advanced(
    p_id BIGINT,
    p_close_price NUMERIC
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_prediction RECORD;
    v_price_change NUMERIC;
    v_price_change_percent NUMERIC;
    v_status TEXT;
    v_payout INTEGER := 0;
    v_profit INTEGER := 0;
    v_result JSON;
BEGIN
    -- 1. Fetch Prediction (Lock)
    SELECT * INTO v_prediction
    FROM predictions
    WHERE id = p_id AND status = 'pending'
    FOR UPDATE;
    
    IF NOT FOUND THEN
        RETURN json_build_object(
            'success', false,
            'error', 'Prediction not found or already resolved'
        );
    END IF;
    
    -- 2. Calculate Change
    v_price_change := p_close_price - v_prediction.entry_price;
    v_price_change_percent := abs(v_price_change / v_prediction.entry_price * 100);
    
    -- 3. Determine Outcome
    IF v_prediction.direction = 'UP' THEN
        IF v_price_change > 0 AND v_price_change_percent >= v_prediction.target_percent THEN
            v_status := 'WIN';
            v_payout := v_prediction.bet_amount * (v_prediction.target_percent * 2 + 1);
        ELSIF v_price_change < 0 THEN
            v_status := 'LOSS';
            v_payout := 0;
        ELSE
            v_status := 'ND';
            v_payout := v_prediction.bet_amount;
        END IF;
    ELSIF v_prediction.direction = 'DOWN' THEN
        IF v_price_change < 0 AND v_price_change_percent >= v_prediction.target_percent THEN
            v_status := 'WIN';
            v_payout := v_prediction.bet_amount * (v_prediction.target_percent * 2 + 1);
        ELSIF v_price_change > 0 THEN
            v_status := 'LOSS';
            v_payout := 0;
        ELSE
            v_status := 'ND';
            v_payout := v_prediction.bet_amount;
        END IF;
    END IF;
    
    v_profit := v_payout - v_prediction.bet_amount;

    -- 4. Update Prediction
    UPDATE predictions
    SET 
        status = v_status,
        actual_price = p_close_price,
        profit = v_profit,
        resolved_at = now()
    WHERE id = p_id;
    
    -- 5. Payout Points
    IF v_payout > 0 THEN
        UPDATE profiles
        SET points = points + v_payout
        WHERE id = v_prediction.user_id;
    END IF;
    
    -- 6. Create Notification with points_change
    INSERT INTO notifications (user_id, type, message, prediction_id, points_change)
    VALUES (
        v_prediction.user_id,
        'prediction_resolved',
        format('%s prediction: %s (%s pts)', v_prediction.asset_symbol, v_status, v_profit),
        p_id,
        v_profit
    );
    
    -- 7. Return Result
    v_result := json_build_object(
        'success', true,
        'status', v_status,
        'payout', v_payout,
        'profit', v_profit,
        'price_change_percent', v_price_change_percent
    );
    
    RETURN v_result;
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object(
            'success', false,
            'error', SQLERRM
        );
END;
$$;
-- 🚀 ROBUST FIX: Clean up all overloads and Restore Prediction Functionality
-- This script drops ALL versions of submit_prediction to avoid "best candidate function" errors.

DO $$ 
DECLARE 
    r RECORD;
BEGIN
    -- Drop every function named 'submit_prediction' regardless of arguments
    FOR r IN (SELECT oid::regprocedure FROM pg_proc WHERE proname = 'submit_prediction' AND pronamespace = 'public'::regnamespace) LOOP
        EXECUTE 'DROP FUNCTION ' || r.oid::regprocedure;
    END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public.submit_prediction(
    p_user_id UUID,
    p_asset_symbol TEXT,
    p_timeframe TEXT,
    p_direction TEXT,
    p_target_percent NUMERIC,
    p_entry_price NUMERIC,
    p_bet_amount INTEGER
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_current_points INTEGER;
    v_new_points INTEGER;
    v_candle_duration BIGINT;
    v_candle_close_at TIMESTAMP WITH TIME ZONE;
    v_prediction_id BIGINT;
BEGIN
    -- 1. Check & Lock Points
    SELECT points INTO v_current_points FROM profiles WHERE id = p_user_id FOR UPDATE;
    
    IF v_current_points < p_bet_amount THEN
        RETURN json_build_object('success', false, 'error', 'Insufficient points');
    END IF;
    
    -- 2. Calculate Alignment
    CASE 
        WHEN p_timeframe ~ '^\d+m$' THEN v_candle_duration := (regexp_replace(p_timeframe, '[^0-9]', '', 'g')::INTEGER) * 60;
        WHEN p_timeframe ~ '^\d+h$' THEN v_candle_duration := (regexp_replace(p_timeframe, '[^0-9]', '', 'g')::INTEGER) * 3600;
        WHEN p_timeframe ~ '^\d+d$' THEN v_candle_duration := (regexp_replace(p_timeframe, '[^0-9]', '', 'g')::INTEGER) * 86400;
        ELSE v_candle_duration := 900;
    END CASE;

    v_candle_close_at := to_timestamp(floor(extract(epoch from now()) / v_candle_duration) * v_candle_duration + v_candle_duration);

    -- 3. Insert Prediction
    INSERT INTO predictions (user_id, asset_symbol, timeframe, direction, target_percent, entry_price, bet_amount, status, candle_close_at)
    VALUES (p_user_id, p_asset_symbol, p_timeframe, p_direction, p_target_percent, p_entry_price, p_bet_amount, 'pending', v_candle_close_at)
    RETURNING id INTO v_prediction_id;

    -- 4. Deduct Points
    UPDATE profiles SET points = points - p_bet_amount WHERE id = p_user_id RETURNING points INTO v_new_points;

    -- Audit Log skipped to avoid "Table Not Found" error
    
    RETURN json_build_object('success', true, 'prediction_id', v_prediction_id, 'new_points', v_new_points);
END;
$$;
-- 1. [CLEANUP] Drop previous versions to avoid signature mismatch
DROP FUNCTION IF EXISTS public.get_top_leaders(integer);

-- 2. [RESTORE] Restore get_top_leaders
CREATE OR REPLACE FUNCTION get_top_leaders(limit_count int DEFAULT 5)
RETURNS TABLE (
    id uuid,
    username text,
    avatar_url text,
    points int,
    total_wins int
)
LANGUAGE sql
SECURITY DEFINER -- Use security definer to access profiles bypassing RLS
SET search_path = public
AS $$
  SELECT 
    id, 
    username, 
    NULL as avatar_url, -- Column does not exist in profiles, returning NULL
    COALESCE(points, 0) as points, 
    COALESCE(total_wins, 0) as total_wins
  FROM profiles
  WHERE points < 1000000 -- Exclude AI users who have 1M+ points
  AND username NOT LIKE 'Analyst_%' -- Safety check for AI naming convention
  ORDER BY points DESC
  LIMIT limit_count;
$$;
-- 1. [CLEANUP] Drop previous versions to avoid signature mismatch
DROP FUNCTION IF EXISTS public.get_trending_assets(integer);

-- 2. [RESTORE] Restore get_trending_assets
CREATE OR REPLACE FUNCTION get_trending_assets(limit_count int)
RETURNS TABLE (
  symbol text,
  asset_type text,
  timeframe text,
  prediction_count bigint,
  total_volume bigint
) 
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    p.asset_symbol as symbol,
    MAX(p.asset_type) as asset_type, -- Mocking asset_type from predictions table structure if needed, or joining with assets table. Assuming consistent type per symbol.
    p.timeframe,
    COUNT(*) as prediction_count,
    COALESCE(SUM(p.bet_amount), 0) as total_volume
  FROM predictions p
  WHERE p.status = 'pending'
  GROUP BY p.asset_symbol, p.timeframe
  ORDER BY total_volume DESC, prediction_count DESC
  LIMIT limit_count;
END;
$$;

-- 1. DROP all possible overloaded signatures to clear ambiguity
DROP FUNCTION IF EXISTS public.submit_prediction(uuid, text, text, text, numeric, numeric, integer);
DROP FUNCTION IF EXISTS public.submit_prediction(uuid, text, text, text, numeric, numeric, integer, boolean, text);
DROP FUNCTION IF EXISTS public.submit_prediction(uuid, text, text, text, numeric, numeric, numeric);

-- 2. CREATE the clean version (No dependency on activity_logs)
CREATE OR REPLACE FUNCTION public.submit_prediction(
    p_user_id UUID,
    p_asset_symbol TEXT,
    p_timeframe TEXT,
    p_direction TEXT,
    p_bet_amount INTEGER,
    p_target_percent NUMERIC,
    p_entry_price NUMERIC
)
RETURNS SETOF public.predictions
LANGUAGE plpgsql
AS $function$
DECLARE
    v_prediction_id UUID;
    v_user_email TEXT;
BEGIN
    -- Check points
    IF NOT EXISTS (
        SELECT 1 FROM profiles 
        WHERE id = p_user_id AND points >= p_bet_amount
    ) THEN
        RAISE EXCEPTION 'Insufficient points';
    END IF;

    -- Update points
    UPDATE profiles 
    SET points = points - p_bet_amount 
    WHERE id = p_user_id;

    -- Create prediction
    INSERT INTO predictions (
        user_id,
        asset_symbol,
        timeframe,
        direction,
        bet_amount,
        target_percent,
        entry_price,
        status,
        created_at
    )
    VALUES (
        p_user_id,
        p_asset_symbol,
        p_timeframe,
        p_direction,
        p_bet_amount,
        p_target_percent,
        p_entry_price,
        'PENDING',
        NOW()
    )
    RETURNING id INTO v_prediction_id;

    -- Return the created prediction
    RETURN QUERY SELECT * FROM predictions WHERE id = v_prediction_id;
END;
$function$;
