export const DISPOSABLE_EMAIL_DOMAINS = [
    "temp-mail.org", "10minutemail.com", "guerrillamail.com", "maildrop.cc",
    "mailinator.com", "dispostable.com", "throwawaymail.com", "getnada.com",
    "yopmail.com", "sharklasers.com", "mail-temp.com", "tempmail.net",
    "click-away.ru", "tempail.com", "emailondeck.com", "owlymail.com",
    "moakt.com", "mail.tm", "mail.gw", "crazymailing.com", "tempmailaddress.com",
    "mintemail.com", "block-spam.com", "instant-mail.io", "dropmail.me",
    "10mail.org", "tempmail.com", "temp-mail.io", "nada.ltd", "nada.email",
    "duck.com", "anonaddy.com", "anonaddy.me", "simplelogin.com", "simplelogin.co",
    "simplelogin.fr", "trashmail.com", "trashmail.net", "trashmail.org",
    "trashmail.me", "tempmail.de", "tempmail.at", "tempmail.ch", "mailinator.net",
    "sogetthis.com", "spam4.me", "spamgourmet.com", "my10minutemail.com",
    "temp-mail.ru", "zillamail.com", "mailsac.com", "tempmail.ninja",
    "inboxkitten.com", "disposablemail.com", "discard.email", "spambog.com",
    "spambog.de", "spambog.ru", "0815.ru", "brennendesreich.de", "crapmail.org",
    "dodgit.com", "drdrb.com", "drdrb.net", "drdrb.org", "ephemail.net",
    "ghostmail.de", "haltospam.com", "kurzpost.de", "mailcatch.com", "mailexpire.com",
    "mailnesia.com", "meltmail.com", "mintemail.com", "mytemp.email", "nospam.ze.tc",
    "nowmymail.com", "pookmail.com", "rmqkr.net", "shiftmail.com", "spamcorptastic.com",
    "spammotel.com", "spamspot.com", "tempemail.net", "tempr.email", "tradermail.info",
    "wegwerfemail.de", "yopmail.fr", "yopmail.net", "zippymail.info", "mail7.io",
    "vumail.org", "freetempmail.com", "temp-mail.pro", "moakt.cc", "moakt.co",
    "disposable.com", "tmail.ws", "disroot.org", "nospam.at"
];
