-- Final Sync: Audit Logs, Prediction Alignment, and Reward Logic Integration

-- 0. Clean up existing functions to allow type changes
DROP FUNCTION IF EXISTS public.submit_prediction(uuid, text, text, text, numeric, numeric, integer);
DROP FUNCTION IF EXISTS public.resolve_prediction_advanced(bigint, numeric);
DROP FUNCTION IF EXISTS public.resolve_prediction_advanced(bigint, numeric, numeric);

-- 1. Create Activity Logs Table for Auditability
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    action_type TEXT NOT NULL, -- 'BET', 'RESOLVE', 'FEED_POST', 'POINT_CHANGE'
    asset_symbol TEXT,
    prediction_id BIGINT,
    metadata JSONB, -- Store full context (prices, profit, etc.)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_user ON activity_logs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_type ON activity_logs(action_type);

-- 2. Enhanced submit_prediction (Restores Alignment)
CREATE OR REPLACE FUNCTION public.submit_prediction(
    p_user_id UUID,
    p_asset_symbol TEXT,
    p_timeframe TEXT,
    p_direction TEXT,
    p_target_percent NUMERIC,
    p_entry_price NUMERIC,
    p_bet_amount INTEGER
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_current_points INTEGER;
    v_new_points INTEGER;
    v_candle_duration BIGINT;
    v_candle_close_at TIMESTAMP WITH TIME ZONE;
    v_prediction_id BIGINT;
    v_min_bet INTEGER;
BEGIN
    SELECT points INTO v_current_points FROM profiles WHERE id = p_user_id FOR UPDATE;
    v_min_bet := GREATEST(10, FLOOR(v_current_points * 0.01));

    IF v_current_points < p_bet_amount THEN
        RETURN json_build_object('success', false, 'error', 'Insufficient points');
    END IF;

    -- Calculate Alignment
    CASE 
        WHEN p_timeframe ~ '^\d+m$' THEN v_candle_duration := (regexp_replace(p_timeframe, '[^0-9]', '', 'g')::INTEGER) * 60;
        WHEN p_timeframe ~ '^\d+h$' THEN v_candle_duration := (regexp_replace(p_timeframe, '[^0-9]', '', 'g')::INTEGER) * 3600;
        WHEN p_timeframe ~ '^\d+d$' THEN v_candle_duration := (regexp_replace(p_timeframe, '[^0-9]', '', 'g')::INTEGER) * 86400;
        ELSE v_candle_duration := 900;
    END CASE;

    v_candle_close_at := to_timestamp(floor(extract(epoch from now()) / v_candle_duration) * v_candle_duration + v_candle_duration);

    INSERT INTO predictions (user_id, asset_symbol, timeframe, direction, target_percent, entry_price, bet_amount, status, candle_close_at)
    VALUES (p_user_id, p_asset_symbol, p_timeframe, p_direction, p_target_percent, p_entry_price, p_bet_amount, 'pending', v_candle_close_at)
    RETURNING id INTO v_prediction_id;

    UPDATE profiles SET points = points - p_bet_amount WHERE id = p_user_id RETURNING points INTO v_new_points;

    -- AUDIT LOG: Record Betting Action
    INSERT INTO activity_logs (user_id, action_type, asset_symbol, prediction_id, metadata)
    VALUES (p_user_id, 'BET', p_asset_symbol, v_prediction_id, json_build_object(
        'bet_amount', p_bet_amount,
        'entry_price', p_entry_price,
        'target_percent', p_target_percent,
        'timeframe', p_timeframe,
        'direction', p_direction,
        'candle_close_at', v_candle_close_at
    ));

    RETURN json_build_object('success', true, 'prediction_id', v_prediction_id, 'new_points', v_new_points);
END;
$$;

-- 3. Enhanced resolve_prediction_advanced (Audit + Latest Rewards)
CREATE OR REPLACE FUNCTION public.resolve_prediction_advanced(
    p_id BIGINT,
    p_close_price NUMERIC,
    p_open_price NUMERIC DEFAULT NULL
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_prediction RECORD;
    v_profile RECORD;
    v_price_change NUMERIC;
    v_price_change_percent NUMERIC;
    v_status TEXT;
    v_is_dir_correct BOOLEAN;
    v_is_target_hit BOOLEAN;
    v_direction_profit NUMERIC := 0;
    v_target_bonus INTEGER := 0;
    v_base_profit NUMERIC := 0;
    v_final_profit NUMERIC := 0;
    v_payout INTEGER := 0;
    v_tf_mult NUMERIC;
    v_streak_mult NUMERIC;
    c_house_edge NUMERIC := 0.95;
    v_new_streak INTEGER;
    v_open_price NUMERIC;
BEGIN
    SELECT * INTO v_prediction FROM predictions WHERE id = p_id AND status = 'pending' FOR UPDATE;
    IF NOT FOUND THEN RETURN json_build_object('success', false, 'error', 'Already resolved'); END IF;
    
    -- Ensure we use the best available open price
    v_open_price := COALESCE(p_open_price, v_prediction.entry_price);

    SELECT * INTO v_profile FROM profiles WHERE id = v_prediction.user_id FOR UPDATE;

    v_price_change := p_close_price - v_open_price;
    v_price_change_percent := abs(v_price_change / v_open_price * 100);

    -- Outcome logic (Condensed)
    v_is_dir_correct := (v_prediction.direction = 'UP' AND v_price_change > 0) OR (v_prediction.direction = 'DOWN' AND v_price_change < 0);
    v_is_target_hit := (v_price_change_percent >= v_prediction.target_percent);

    IF v_is_dir_correct THEN
        v_status := 'WIN';
        CASE v_prediction.timeframe 
            WHEN '30m' THEN v_tf_mult := 1.1; WHEN '1h' THEN v_tf_mult := 1.2; WHEN '4h' THEN v_tf_mult := 1.5; WHEN '1d' THEN v_tf_mult := 1.8; ELSE v_tf_mult := 1.0;
        END CASE;
        v_direction_profit := v_prediction.bet_amount * 0.8 * v_tf_mult;
        IF v_is_target_hit THEN
            IF v_prediction.target_percent <= 0.5 THEN v_target_bonus := 20; ELSIF v_prediction.target_percent <= 1.0 THEN v_target_bonus := 40; ELSIF v_prediction.target_percent <= 1.5 THEN v_target_bonus := 70; ELSE v_target_bonus := 120; END IF;
            v_new_streak := v_profile.streak + 1;
        ELSE
            v_new_streak := 0;
        END IF;
        IF v_new_streak >= 5 THEN v_streak_mult := 2.5; ELSIF v_new_streak = 4 THEN v_streak_mult := 2.0; ELSIF v_new_streak = 3 THEN v_streak_mult := 1.6; ELSIF v_new_streak = 2 THEN v_streak_mult := 1.3; ELSE v_streak_mult := 1.0; END IF;
        v_final_profit := (v_direction_profit + v_target_bonus) * v_streak_mult * c_house_edge;
        v_payout := v_prediction.bet_amount + ROUND(v_final_profit);
    ELSE
        v_status := 'LOSS'; v_payout := 0; v_final_profit := -v_prediction.bet_amount; v_new_streak := 0;
    END IF;

    UPDATE profiles SET points = points + v_payout, streak = v_new_streak WHERE id = v_prediction.user_id;
    UPDATE predictions SET status = v_status, actual_price = p_close_price, entry_price = v_open_price, profit = ROUND(v_final_profit), resolved_at = now() WHERE id = p_id;
    
    INSERT INTO notifications (user_id, type, message, prediction_id)
    VALUES (v_prediction.user_id, 'prediction_resolved', format('%s: %s (%s pts)', v_prediction.asset_symbol, v_status, ROUND(v_final_profit)), p_id);

    -- AUDIT LOG: Record Resolution Action
    INSERT INTO activity_logs (user_id, action_type, asset_symbol, prediction_id, metadata)
    VALUES (v_prediction.user_id, 'RESOLVE', v_prediction.asset_symbol, p_id, json_build_object(
        'status', v_status,
        'open_price', v_open_price,
        'close_price', p_close_price,
        'profit', ROUND(v_final_profit),
        'payout', v_payout,
        'streak', v_new_streak,
        'is_target_hit', v_is_target_hit
    ));

    RETURN json_build_object('success', true, 'status', v_status, 'profit', ROUND(v_final_profit));
END;
$$;
