-- Create Posts Table (The core content table)
create table if not exists posts (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null, -- references auth user directly or profiles
    title text,
    content text,
    
    -- Metadata from prediction/insight
    asset_symbol text,
    timeframe text,
    direction text, -- 'UP', 'DOWN', 'NEUTRAL'
    volatility_target numeric default 0,
    
    -- Metrics (Denormalized for performance)
    likes_count int default 0,
    comments_count int default 0,
    bookmarks_count int default 0,
    shares_count int default 0,
    
    -- Feed Algorithm Scores
    feed_score int default 0,
    freshness_score int default 0,
    engagement_score int default 0,
    author_score int default 0,
    
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table posts enable row level security;

-- Policies
DROP POLICY IF EXISTS "Public posts are viewable by everyone" ON posts;
create policy "Public posts are viewable by everyone" on posts for select using (true);

DROP POLICY IF EXISTS "Users can insert their own posts" ON posts;
create policy "Users can insert their own posts" on posts for insert with check (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own posts" ON posts;
create policy "Users can update their own posts" on posts for update using (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own posts" ON posts;
create policy "Users can delete their own posts" on posts for delete using (auth.uid() = user_id);

-- Index for Feed
create index if not exists idx_posts_feed_score on posts (feed_score desc);
create index if not exists idx_posts_created_at on posts (created_at desc);

-- Note: After this is created, you can run the 'interaction tables' migration.
-- If you already ran create_interaction_tables.sql and it failed, run this, then run that one again.
