-- ============================================
-- 1. Profiles Table
-- ============================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  email TEXT,
  username TEXT,
  points INTEGER DEFAULT 1000 CHECK (points >= 0),
  tier TEXT DEFAULT 'bronze',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
CREATE POLICY "Users can insert their own profile." ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
CREATE POLICY "Users can update own profile." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- ============================================
-- 2. New User Trigger
-- ============================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, username, points)
  VALUES (new.id, new.email, split_part(new.email, '@', 1), 1000)
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ============================================
-- 3. Predictions Table (Complete Rebuild)
-- ============================================
DROP TABLE IF EXISTS public.predictions CASCADE;

CREATE TABLE public.predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  
  -- Prediction Info
  asset_symbol TEXT NOT NULL,
  timeframe TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('UP', 'DOWN')),
  target_percent NUMERIC NOT NULL CHECK (target_percent IN (0.5, 1.0, 1.5, 2.0)),
  entry_price NUMERIC NOT NULL CHECK (entry_price > 0),
  bet_amount INTEGER NOT NULL CHECK (bet_amount > 0 AND bet_amount <= 1000),
  
  -- Results
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'WIN', 'LOSS', 'ND')),
  actual_price NUMERIC,
  profit INTEGER DEFAULT 0,
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  candle_close_at TIMESTAMP WITH TIME ZONE NOT NULL,
  resolved_at TIMESTAMP WITH TIME ZONE,
  
  -- Comments
  comment TEXT CHECK (char_length(comment) <= 140)
);

-- Performance Indexes
CREATE INDEX idx_predictions_status ON predictions(status);
CREATE INDEX idx_predictions_user ON predictions(user_id);
CREATE INDEX idx_predictions_candle ON predictions(asset_symbol, timeframe, candle_close_at);
CREATE INDEX idx_predictions_created ON predictions(created_at DESC);

-- RLS
ALTER TABLE public.predictions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Predictions are viewable by everyone." ON public.predictions;
CREATE POLICY "Predictions are viewable by everyone." ON public.predictions
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own predictions." ON public.predictions;
CREATE POLICY "Users can insert their own predictions." ON public.predictions
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ============================================
-- 4. Notifications Table (Realtime)
-- ============================================
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  type TEXT NOT NULL,
  message TEXT,
  prediction_id BIGINT REFERENCES public.predictions(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  read BOOLEAN DEFAULT false
);

CREATE INDEX idx_notifications_user ON notifications(user_id, created_at DESC);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own notifications" ON public.notifications;
CREATE POLICY "Users can view own notifications" ON public.notifications
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert notifications" ON public.notifications;
CREATE POLICY "Users can insert notifications" ON public.notifications
  FOR INSERT WITH CHECK (true); -- Public for Cron/RPC usage

-- ============================================
-- 5. RPC Function 1: submit_prediction
-- ============================================
DROP FUNCTION IF EXISTS public.submit_prediction CASCADE;

CREATE OR REPLACE FUNCTION public.submit_prediction(
    p_user_id UUID,
    p_asset_symbol TEXT,
    p_timeframe TEXT,
    p_direction TEXT,
    p_target_percent NUMERIC,
    p_entry_price NUMERIC,
    p_bet_amount INTEGER
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_current_points INTEGER;
    v_new_points INTEGER;
    v_candle_duration BIGINT;
    v_candle_close_at TIMESTAMP WITH TIME ZONE;
    v_prediction_id BIGINT;
BEGIN
    -- 1. Check & Lock Points
    SELECT points INTO v_current_points
    FROM profiles
    WHERE id = p_user_id
    FOR UPDATE;
    
    -- 2. Validate Points
    IF v_current_points < p_bet_amount THEN
        RETURN json_build_object(
            'success', false,
            'error', 'Insufficient points',
            'current_points', v_current_points
        );
    END IF;
    
    -- 3. Min/Max Checks
    IF p_bet_amount < 10 THEN
        RETURN json_build_object(
            'success', false,
            'error', 'Minimum bet is 10 points'
        );
    END IF;
    
    IF p_bet_amount > v_current_points * 0.2 AND v_current_points > 50 THEN
        RETURN json_build_object(
            'success', false,
            'error', 'Maximum bet is 20% of your points'
        );
    END IF;
    
    -- 4. Calculate Close Time
    CASE
        WHEN p_timeframe ~ '^\d+m$' THEN
            v_candle_duration := (regexp_replace(p_timeframe, '[^0-9]', '', 'g')::INTEGER) * 60;
        WHEN p_timeframe ~ '^\d+h$' THEN
            v_candle_duration := (regexp_replace(p_timeframe, '[^0-9]', '', 'g')::INTEGER) * 3600;
        WHEN p_timeframe ~ '^\d+d$' THEN
            v_candle_duration := (regexp_replace(p_timeframe, '[^0-9]', '', 'g')::INTEGER) * 86400;
        ELSE
            v_candle_duration := 900; -- default 15m
    END CASE;
    
    v_candle_close_at := to_timestamp(
        floor(extract(epoch from now()) / v_candle_duration) * v_candle_duration + v_candle_duration
    );
    
    -- 5. Deduct Points
    v_new_points := v_current_points - p_bet_amount;
    
    UPDATE profiles
    SET points = v_new_points
    WHERE id = p_user_id;
    
    -- 6. Create Prediction
    INSERT INTO predictions (
        user_id,
        asset_symbol,
        timeframe,
        direction,
        target_percent,
        entry_price,
        bet_amount,
        candle_close_at,
        status
    ) VALUES (
        p_user_id,
        p_asset_symbol,
        p_timeframe,
        p_direction,
        p_target_percent,
        p_entry_price,
        p_bet_amount,
        v_candle_close_at,
        'pending'
    )
    RETURNING id INTO v_prediction_id;
    
    -- 7. Return Success
    RETURN json_build_object(
        'success', true,
        'prediction_id', v_prediction_id,
        'new_points', v_new_points,
        'candle_close_at', v_candle_close_at
    );
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object(
            'success', false,
            'error', SQLERRM
        );
END;
$$;

-- ============================================
-- 6. RPC Function 2: resolve_prediction_advanced
-- ============================================
DROP FUNCTION IF EXISTS public.resolve_prediction_advanced CASCADE;

CREATE OR REPLACE FUNCTION public.resolve_prediction_advanced(
    p_id BIGINT,
    p_close_price NUMERIC
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_prediction RECORD;
    v_price_change NUMERIC;
    v_price_change_percent NUMERIC;
    v_status TEXT;
    v_payout INTEGER := 0;
    v_result JSON;
BEGIN
    -- 1. Fetch Prediction (Lock)
    SELECT * INTO v_prediction
    FROM predictions
    WHERE id = p_id AND status = 'pending'
    FOR UPDATE;
    
    IF NOT FOUND THEN
        RETURN json_build_object(
            'success', false,
            'error', 'Prediction not found or already resolved'
        );
    END IF;
    
    -- 2. Calculate Change
    v_price_change := p_close_price - v_prediction.entry_price;
    v_price_change_percent := abs(v_price_change / v_prediction.entry_price * 100);
    
    -- 3. Determine Outcome
    IF v_prediction.direction = 'UP' THEN
        IF v_price_change > 0 AND v_price_change_percent >= v_prediction.target_percent THEN
            v_status := 'WIN';
            v_payout := v_prediction.bet_amount * (v_prediction.target_percent * 2 + 1);
        ELSIF v_price_change < 0 THEN
            v_status := 'LOSS';
            v_payout := 0;
        ELSE
            v_status := 'ND';
            v_payout := v_prediction.bet_amount;
        END IF;
    ELSIF v_prediction.direction = 'DOWN' THEN
        IF v_price_change < 0 AND v_price_change_percent >= v_prediction.target_percent THEN
            v_status := 'WIN';
            v_payout := v_prediction.bet_amount * (v_prediction.target_percent * 2 + 1);
        ELSIF v_price_change > 0 THEN
            v_status := 'LOSS';
            v_payout := 0;
        ELSE
            v_status := 'ND';
            v_payout := v_prediction.bet_amount;
        END IF;
    END IF;
    
    -- 4. Update Prediction
    UPDATE predictions
    SET 
        status = v_status,
        actual_price = p_close_price,
        profit = v_payout - v_prediction.bet_amount,
        resolved_at = now()
    WHERE id = p_id;
    
    -- 5. Payout Points
    IF v_payout > 0 THEN
        UPDATE profiles
        SET points = points + v_payout
        WHERE id = v_prediction.user_id;
    END IF;
    
    -- 6. Create Notification (CRITICAL for Realtime!)
    INSERT INTO notifications (user_id, type, message, prediction_id)
    VALUES (
        v_prediction.user_id,
        'prediction_resolved',
        format('%s prediction: %s (%s pts)', v_prediction.asset_symbol, v_status, v_payout - v_prediction.bet_amount),
        p_id
    );
    
    -- 7. Return Result
    v_result := json_build_object(
        'success', true,
        'status', v_status,
        'payout', v_payout,
        'profit', v_payout - v_prediction.bet_amount,
        'price_change_percent', v_price_change_percent
    );
    
    RETURN v_result;
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object(
            'success', false,
            'error', SQLERRM
        );
END;
$$;

-- ============================================
-- 7. Drop Unused Tables
-- ============================================
DROP TABLE IF EXISTS public.comments CASCADE;
