-- ==============================================================================
-- 🚀 VIBE FORECAST: FULL RESET & FRESH START (PRODUCTION BASELINE)
-- 이 스크립트는 개발 환경의 모든 데이터(사용자 포함)를 삭제하고, 
-- 상용망과 100% 동일한 기능 구조(Schema)만 남긴 텅 빈 상태로 만듭니다.
-- ==============================================================================

-- 1. 모든 데이터 삭제 (Wipe everything)
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

-- auth 데이터 삭제 (CASCADE로 인해 관련된 모든 public 데이터도 같이 날아갑니다)
-- 주의: 이 명령은 'postgres' 권한으로 실행해야 합니다.
TRUNCATE auth.users CASCADE;

-- 2. 기본 권한 복구
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO anon;
GRANT ALL ON SCHEMA public TO authenticated;
GRANT ALL ON SCHEMA public TO service_role;

-- 3. [PROFILES] 테이블 및 트리거
CREATE TABLE public.profiles (
  id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  email TEXT,
  username TEXT,
  points INTEGER DEFAULT 1000 CHECK (points >= 0),
  tier TEXT DEFAULT 'bronze',
  streak INTEGER DEFAULT 0,
  streak_count INTEGER DEFAULT 0,
  total_games INTEGER DEFAULT 0,
  total_wins INTEGER DEFAULT 0,
  total_earnings INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public view" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Self update" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, username, points)
  VALUES (new.id, new.email, split_part(new.email, '@', 1), 1000)
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 4. [PREDICTIONS] 테이블
CREATE TABLE public.predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  asset_symbol TEXT NOT NULL,
  timeframe TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('UP', 'DOWN')),
  target_percent NUMERIC NOT NULL,
  entry_price NUMERIC NOT NULL,
  bet_amount INTEGER NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'WIN', 'LOSS', 'ND')),
  actual_price NUMERIC,
  profit INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  candle_close_at TIMESTAMP WITH TIME ZONE NOT NULL,
  resolved_at TIMESTAMP WITH TIME ZONE,
  comment TEXT CHECK (char_length(comment) <= 140)
);

ALTER TABLE public.predictions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public view predictions" ON public.predictions FOR SELECT USING (true);
CREATE POLICY "Users insert predictions" ON public.predictions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update comments" ON public.predictions FOR UPDATE USING (auth.uid() = user_id);

-- 5. [NOTIFICATIONS] 테이블
CREATE TABLE public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  type TEXT NOT NULL,
  title TEXT,
  message TEXT,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users view notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "System insert notifications" ON public.notifications FOR INSERT WITH CHECK (true);

-- 6. 핵심 RPC 함수들 (Production Stable Logic)
-- RPC 1: get_user_rank
CREATE OR REPLACE FUNCTION public.get_user_rank(p_user_id UUID)
RETURNS BIGINT
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
    SELECT rank
    FROM (
        SELECT id, RANK() OVER (ORDER BY points DESC) as rank
        FROM public.profiles
    ) as ranked_users
    WHERE id = p_user_id;
$$;

-- RPC 2: submit_prediction
CREATE OR REPLACE FUNCTION public.submit_prediction(
  p_user_id UUID,
  p_asset_symbol TEXT,
  p_timeframe TEXT,
  p_direction TEXT,
  p_target_percent NUMERIC,
  p_entry_price NUMERIC,
  p_bet_amount INTEGER
) RETURNS JSONB AS $$
DECLARE
  v_user_points INTEGER;
  v_prediction_id BIGINT;
  v_interval INTERVAL;
  v_candle_close TIMESTAMP WITH TIME ZONE;
BEGIN
  IF p_timeframe = '1m' THEN v_interval := INTERVAL '1 minute';
  ELSIF p_timeframe = '5m' THEN v_interval := INTERVAL '5 minutes';
  ELSIF p_timeframe = '15m' THEN v_interval := INTERVAL '15 minutes';
  ELSIF p_timeframe = '30m' THEN v_interval := INTERVAL '30 minutes';
  ELSIF p_timeframe = '1h' THEN v_interval := INTERVAL '1 hour';
  ELSIF p_timeframe = '4h' THEN v_interval := INTERVAL '4 hours';
  ELSIF p_timeframe = '1d' THEN v_interval := INTERVAL '1 day';
  ELSE v_interval := INTERVAL '1 hour';
  END IF;

  v_candle_close := date_bin(v_interval, now(), '2000-01-01'::timestamp with time zone) + v_interval;
  SELECT points INTO v_user_points FROM profiles WHERE id = p_user_id FOR UPDATE;
  IF v_user_points < p_bet_amount THEN RAISE EXCEPTION 'Insufficient points'; END IF;
  UPDATE profiles SET points = points - p_bet_amount WHERE id = p_user_id;

  INSERT INTO predictions (
    user_id, asset_symbol, timeframe, direction, target_percent, 
    entry_price, status, bet_amount, candle_close_at, created_at
  ) VALUES (
    p_user_id, p_asset_symbol, p_timeframe, p_direction, p_target_percent, 
    p_entry_price, 'pending', p_bet_amount, v_candle_close, now()
  ) RETURNING id INTO v_prediction_id;

  RETURN jsonb_build_object('success', true, 'prediction_id', v_prediction_id, 'new_points', v_user_points - p_bet_amount);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RPC 3: resolve_prediction_advanced
CREATE OR REPLACE FUNCTION public.resolve_prediction_advanced(
    p_id BIGINT,
    p_close_price NUMERIC,
    p_open_price NUMERIC DEFAULT NULL
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_prediction RECORD;
    v_profile RECORD;
    v_price_change NUMERIC;
    v_price_change_percent NUMERIC;
    v_status TEXT;
    v_is_dir_correct BOOLEAN;
    v_is_target_hit BOOLEAN;
    v_final_profit NUMERIC := 0;
    v_payout INTEGER := 0;
    v_tf_mult NUMERIC;
    v_streak_mult NUMERIC;
    v_new_streak INTEGER;
    v_open_price NUMERIC;
    v_target_bonus INTEGER := 0;
BEGIN
    SELECT * INTO v_prediction FROM predictions WHERE id = p_id AND status = 'pending' FOR UPDATE;
    IF NOT FOUND THEN RETURN json_build_object('success', false, 'error', 'Already resolved'); END IF;
    
    v_open_price := COALESCE(p_open_price, v_prediction.entry_price);
    SELECT * INTO v_profile FROM profiles WHERE id = v_prediction.user_id FOR UPDATE;

    v_price_change := p_close_price - v_open_price;
    v_price_change_percent := abs(v_price_change / v_open_price * 100);

    v_is_dir_correct := (v_prediction.direction = 'UP' AND v_price_change > 0) OR (v_prediction.direction = 'DOWN' AND v_price_change < 0);
    v_is_target_hit := (v_price_change_percent >= v_prediction.target_percent);

    IF v_is_dir_correct THEN
        v_status := 'WIN';
        CASE v_prediction.timeframe 
            WHEN '30m' THEN v_tf_mult := 1.2; WHEN '1h' THEN v_tf_mult := 1.5; WHEN '4h' THEN v_tf_mult := 2.2; WHEN '1d' THEN v_tf_mult := 3.0; ELSE v_tf_mult := 1.0;
        END CASE;
        
        IF v_is_target_hit THEN
            IF v_prediction.target_percent <= 0.5 THEN v_target_bonus := 20; ELSIF v_prediction.target_percent <= 1.0 THEN v_target_bonus := 40; ELSIF v_prediction.target_percent <= 1.5 THEN v_target_bonus := 70; ELSE v_target_bonus := 120; END IF;
            v_new_streak := COALESCE(v_profile.streak, 0) + 1;
        ELSE
            v_new_streak := 0;
        END IF;

        IF v_new_streak >= 5 THEN v_streak_mult := 2.5; ELSIF v_new_streak = 4 THEN v_streak_mult := 2.0; ELSIF v_new_streak = 3 THEN v_streak_mult := 1.6; ELSIF v_new_streak = 2 THEN v_streak_mult := 1.3; ELSE v_streak_mult := 1.0; END IF;
        v_final_profit := (v_prediction.bet_amount * 0.8 * v_tf_mult + v_target_bonus) * v_streak_mult * 0.95;
        v_payout := v_prediction.bet_amount + ROUND(v_final_profit);
    ELSIF v_price_change = 0 THEN
        v_status := 'ND'; v_payout := v_prediction.bet_amount; v_final_profit := 0; v_new_streak := COALESCE(v_profile.streak, 0);
    ELSE
        v_status := 'LOSS'; v_payout := 0; v_final_profit := -v_prediction.bet_amount; v_new_streak := 0;
    END IF;

    UPDATE profiles SET points = points + v_payout, streak = v_new_streak, streak_count = CASE WHEN v_new_streak > streak_count THEN v_new_streak ELSE streak_count END, total_games = total_games + 1, total_wins = CASE WHEN v_status = 'WIN' THEN total_wins + 1 ELSE total_wins END WHERE id = v_prediction.user_id;
    UPDATE predictions SET status = v_status, actual_price = p_close_price, entry_price = v_open_price, profit = ROUND(v_final_profit), resolved_at = now() WHERE id = p_id;
    INSERT INTO notifications (user_id, type, message, prediction_id) VALUES (v_prediction.user_id, 'prediction_resolved', format('%s: %s (%s pts)', v_prediction.asset_symbol, v_status, ROUND(v_final_profit)), p_id);

    RETURN json_build_object('success', true, 'status', v_status, 'profit', ROUND(v_final_profit));
END;
$$;

-- 7. 명시적 권한 설정 (Grant explicit permissions)
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO anon;
GRANT ALL ON SCHEMA public TO authenticated;
GRANT ALL ON SCHEMA public TO service_role;

GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;

-- 8. REALTIME 설정
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        CREATE PUBLICATION supabase_realtime;
    END IF;
    BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE profiles, predictions, notifications; EXCEPTION WHEN others THEN NULL; END;
END $$;
