
-- ==============================================================================
-- 🚀 CHARTCLASH: MASTER NUCLEAR RESET (FEBRUARY 12, 2026)
-- This script WIPES everything and restores the TRUE ORIGINAL logic.
-- Logic: Direction Correct = WIN (Regardless of Target Hit).
-- ==============================================================================

-- 0. CLEANUP (Wipe existing schema)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP FUNCTION IF EXISTS public.submit_prediction CASCADE;
DROP FUNCTION IF EXISTS public.resolve_prediction_advanced CASCADE;
DROP FUNCTION IF EXISTS public.get_ranked_insights CASCADE;

DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.prediction_likes CASCADE;
DROP TABLE IF EXISTS public.predictions CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.posts CASCADE;
DROP TABLE IF EXISTS public.likes CASCADE;
DROP TABLE IF EXISTS public.comments CASCADE;
DROP TABLE IF EXISTS public.bookmarks CASCADE;

-- 1. PROFILES TABLE (Original Minimal)
CREATE TABLE public.profiles (
  id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  email TEXT,
  username TEXT,
  points INTEGER DEFAULT 1000 CHECK (points >= 0),
  tier TEXT DEFAULT 'bronze',
  streak INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public view" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Self update" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "System insert" ON public.profiles FOR INSERT WITH CHECK (true);

-- New User Trigger
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, username, points)
  VALUES (new.id, new.email, split_part(new.email, '@', 1), 1000)
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- BACKFILL Existing Users
INSERT INTO public.profiles (id, email, username, points)
SELECT id, email, split_part(email, '@', 1), 1000
FROM auth.users
ON CONFLICT (id) DO NOTHING;

-- 2. PREDICTIONS TABLE (Original Minimal)
CREATE TABLE public.predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  asset_symbol TEXT NOT NULL,
  timeframe TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('UP', 'DOWN')),
  target_percent NUMERIC NOT NULL,
  entry_price NUMERIC NOT NULL,
  bet_amount INTEGER NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'WIN', 'LOSS', 'ND')),
  actual_price NUMERIC,
  profit INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  candle_close_at TIMESTAMP WITH TIME ZONE NOT NULL,
  resolved_at TIMESTAMP WITH TIME ZONE,
  comment TEXT CHECK (char_length(comment) <= 140)
);

ALTER TABLE public.predictions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public view predictions" ON public.predictions FOR SELECT USING (true);
CREATE POLICY "Users insert predictions" ON public.predictions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update comments" ON public.predictions FOR UPDATE USING (auth.uid() = user_id);

CREATE INDEX idx_predictions_user ON predictions(user_id);
CREATE INDEX idx_predictions_status ON predictions(status);

-- 3. NOTIFICATIONS TABLE (Synced with Frontend)
CREATE TABLE public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  type TEXT NOT NULL,
  title TEXT,
  message TEXT,
  points_change INTEGER DEFAULT 0,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users view notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "System insert notifications" ON public.notifications FOR INSERT WITH CHECK (true);

-- 4. RPC: SUBMIT PREDICTION (Stable)
CREATE OR REPLACE FUNCTION public.submit_prediction(
    p_user_id UUID,
    p_asset_symbol TEXT,
    p_timeframe TEXT,
    p_direction TEXT,
    p_target_percent NUMERIC,
    p_entry_price NUMERIC,
    p_bet_amount INTEGER
)
RETURNS JSON LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_current_points INTEGER;
    v_candle_duration BIGINT;
    v_prediction_id BIGINT;
BEGIN
    SELECT points INTO v_current_points FROM profiles WHERE id = p_user_id FOR UPDATE;
    IF v_current_points < p_bet_amount THEN
        RETURN json_build_object('success', false, 'error', 'Insufficient points');
    END IF;

    CASE
        WHEN p_timeframe = '1m' THEN v_candle_duration := 60;
        WHEN p_timeframe = '3m' THEN v_candle_duration := 180;
        WHEN p_timeframe = '5m' THEN v_candle_duration := 300;
        WHEN p_timeframe = '15m' THEN v_candle_duration := 900;
        WHEN p_timeframe = '1h' THEN v_candle_duration := 3600;
        WHEN p_timeframe = '4h' THEN v_candle_duration := 14400;
        WHEN p_timeframe = '1d' THEN v_candle_duration := 86400;
        ELSE v_candle_duration := 900;
    END CASE;

    UPDATE profiles SET points = v_current_points - p_bet_amount WHERE id = p_user_id;

    INSERT INTO predictions (user_id, asset_symbol, timeframe, direction, target_percent, entry_price, bet_amount, candle_close_at)
    VALUES (p_user_id, p_asset_symbol, p_timeframe, p_direction, p_target_percent, p_entry_price, p_bet_amount, 
            to_timestamp(floor(extract(epoch from now()) / v_candle_duration) * v_candle_duration + v_candle_duration))
    RETURNING id INTO v_prediction_id;

    RETURN json_build_object('success', true, 'prediction_id', v_prediction_id);
END;
$$;

-- 5. RPC: RESOLVE PREDICTION (TRUE ORIGINAL LOGIC: DIRECTION = WIN)
CREATE OR REPLACE FUNCTION public.resolve_prediction_advanced(
    p_id BIGINT,
    p_close_price NUMERIC,
    p_open_price NUMERIC DEFAULT NULL
)
RETURNS JSON LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_prediction RECORD;
    v_status TEXT;
    v_is_win BOOLEAN;
    v_payout INTEGER := 0;
    v_profit_pts NUMERIC := 0;
    v_open_price NUMERIC;
BEGIN
    -- 1. Fetch Prediction
    SELECT * INTO v_prediction FROM predictions WHERE id = p_id AND status = 'pending' FOR UPDATE;
    IF NOT FOUND THEN RETURN json_build_object('success', false, 'error', 'Not found'); END IF;
    
    v_open_price := COALESCE(p_open_price, v_prediction.entry_price);

    -- 2. THE TRUE RULE: DIRECTION = WIN
    v_is_win := (v_prediction.direction = 'UP' AND p_close_price > v_open_price) OR 
                (v_prediction.direction = 'DOWN' AND p_close_price < v_open_price);
    
    IF v_is_win THEN
        v_status := 'WIN';
        -- Simple original multiplier logic: 1.8x payout (80% profit)
        v_profit_pts := v_prediction.bet_amount * 0.8;
        v_payout := v_prediction.bet_amount + ROUND(v_profit_pts);
    ELSIF p_close_price = v_open_price THEN
        v_status := 'ND';
        v_payout := v_prediction.bet_amount; -- Refund
        v_profit_pts := 0;
    ELSE
        v_status := 'LOSS';
        v_payout := 0;
        v_profit_pts := -v_prediction.bet_amount;
    END IF;

    -- 3. Update Profile
    UPDATE profiles 
    SET points = points + v_payout,
        streak = (CASE WHEN v_is_win THEN streak + 1 ELSE 0 END)
    WHERE id = v_prediction.user_id;

    -- 4. Update Prediction
    UPDATE predictions 
    SET status = v_status, actual_price = p_close_price, profit = ROUND(v_profit_pts), resolved_at = now() 
    WHERE id = p_id;
    
    -- 5. Notify
    INSERT INTO notifications (user_id, type, title, message, points_change)
    VALUES (v_prediction.user_id, LOWER(v_status), v_prediction.asset_symbol || ' Result',
            format('%s result: %s (%s pts)', v_prediction.asset_symbol, v_status, ROUND(v_profit_pts)),
            ROUND(v_profit_pts));

    RETURN json_build_object('success', true, 'status', v_status, 'profit', ROUND(v_profit_pts));
END;
$$;
