-- ==============================================================================
-- 🚀 CHARTCLASH PRODUCTION FINAL SYNC (2026-02-15)
-- ==============================================================================

-- 0. [SYSTEM CONFIGS] Centralized management for rewards/fees
CREATE TABLE IF NOT EXISTS public.system_configs (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    description TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO public.system_configs (key, value, description) VALUES
('house_edge', '0.95', 'Multiplier for net profit (5% burn)'),
('base_profit_ratio', '0.8', 'Base profit ratio for correct direction'),
('tf_multipliers', '{"1m": 1.0, "5m": 1.0, "15m": 1.0, "30m": 1.1, "1h": 1.2, "4h": 1.5, "1d": 1.8}', 'Timeframe multipliers'),
('target_bonuses', '[{"max": 0.5, "bonus": 20}, {"max": 1.0, "bonus": 40}, {"max": 1.5, "bonus": 70}, {"max": 999, "bonus": 120}]', 'Target hit bonuses'),
('streak_multipliers', '{"2": 1.3, "3": 1.6, "4": 2.0, "5": 2.5}', 'Streak multipliers (key is streak count)'),
('feed_scoring_weights', '{"win_bonus": 40, "target_weight": 15, "like_weight": 2, "win_rate_weight": 0.2, "time_decay": 1.5}', 'Weights for insight feed ranking algorithm')
ON CONFLICT (key) DO NOTHING;

-- 1. [ACTIVITY LOGS] Create table for Auditability
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    action_type TEXT NOT NULL, -- 'BET', 'RESOLVE', 'FEED_POST', 'POINT_CHANGE'
    asset_symbol TEXT,
    prediction_id BIGINT,
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_user ON activity_logs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_type ON activity_logs(action_type);

-- 2. [PROFILES] Add missing gaming stats & tier columns
ALTER TABLE public.profiles 
  ADD COLUMN IF NOT EXISTS total_games INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_wins INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS streak_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS streak INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_earnings INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tier TEXT DEFAULT 'bronze';

-- 3. [NOTIFICATIONS] Sync naming conventions & fields
-- (Improved to handle cases where both 'read' and 'is_read' might exist)
DO $$ 
BEGIN 
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='notifications' AND column_name='read') THEN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='notifications' AND column_name='is_read') THEN
      -- Both exist? Keep is_read, drop old read
      ALTER TABLE public.notifications DROP COLUMN "read";
    ELSE
      -- Only read exists, rename it
      ALTER TABLE public.notifications RENAME COLUMN "read" TO "is_read";
    END IF;
  ELSE
    -- read doesn't exist, ensure is_read is there
    ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT false;
  END IF;
END $$;

ALTER TABLE public.notifications
  ADD COLUMN IF NOT EXISTS title TEXT,
  ADD COLUMN IF NOT EXISTS points_change INTEGER DEFAULT 0;

-- 4. [PREDICTIONS] Alpha Support & Constraint Relaxation
ALTER TABLE public.predictions ADD COLUMN IF NOT EXISTS likes_count INTEGER DEFAULT 0;
ALTER TABLE public.predictions ADD COLUMN IF NOT EXISTS is_opinion BOOLEAN DEFAULT FALSE;

-- Relax Constraints
ALTER TABLE public.predictions DROP CONSTRAINT IF EXISTS predictions_bet_amount_check;
ALTER TABLE public.predictions DROP CONSTRAINT IF EXISTS predictions_entry_price_check;
ALTER TABLE public.predictions DROP CONSTRAINT IF EXISTS predictions_target_percent_check;

ALTER TABLE public.predictions ADD CONSTRAINT predictions_bet_amount_check CHECK (bet_amount >= 0 AND bet_amount <= 1000);
ALTER TABLE public.predictions ADD CONSTRAINT predictions_entry_price_check CHECK (entry_price >= 0);
ALTER TABLE public.predictions ADD CONSTRAINT predictions_target_percent_check CHECK (target_percent >= 0);

-- 5. [PREDICTION LIKES] Support table for Feed Socials
CREATE TABLE IF NOT EXISTS public.prediction_likes (
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  prediction_id BIGINT REFERENCES public.predictions(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (user_id, prediction_id)
);

ALTER TABLE public.prediction_likes ENABLE ROW LEVEL SECURITY;

-- Handle existing policies to avoid duplicate errors
DROP POLICY IF EXISTS "Public view likes" ON prediction_likes;
CREATE POLICY "Public view likes" ON prediction_likes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Auth like prediction" ON prediction_likes;
CREATE POLICY "Auth like prediction" ON prediction_likes FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Auth unlike prediction" ON prediction_likes;
CREATE POLICY "Auth unlike prediction" ON prediction_likes FOR DELETE USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION update_prediction_likes_count()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE public.predictions SET likes_count = likes_count + 1 WHERE id = NEW.prediction_id;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE public.predictions SET likes_count = likes_count - 1 WHERE id = OLD.prediction_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_prediction_like ON public.prediction_likes;
CREATE TRIGGER on_prediction_like
AFTER INSERT OR DELETE ON public.prediction_likes
FOR EACH ROW EXECUTE PROCEDURE update_prediction_likes_count();

-- 6. [RPC] get_ranked_insights (Advanced Sorting + Opinion Filtering)
DROP FUNCTION IF EXISTS public.get_ranked_insights(text, text, text, integer, integer, boolean);
CREATE OR REPLACE FUNCTION public.get_ranked_insights(
  p_asset_symbol TEXT DEFAULT NULL,
  p_timeframe TEXT DEFAULT NULL,
  p_sort_by TEXT DEFAULT 'TOP',
  p_limit INTEGER DEFAULT 20,
  p_offset INTEGER DEFAULT 0,
  p_is_opinion BOOLEAN DEFAULT TRUE 
)
RETURNS TABLE (
  id BIGINT, user_id UUID, username TEXT, tier TEXT, user_win_rate NUMERIC,
  user_total_games INTEGER, asset_symbol TEXT, timeframe TEXT, direction TEXT,
  target_percent NUMERIC, entry_price NUMERIC, status TEXT, profit INTEGER,
  created_at TIMESTAMP WITH TIME ZONE, resolved_at TIMESTAMP WITH TIME ZONE,
  comment TEXT, likes_count INTEGER, insight_score NUMERIC, is_opinion BOOLEAN
) AS $$
DECLARE
  v_weights JSONB;
BEGIN
  -- Fetch weights from config
  SELECT value INTO v_weights FROM system_configs WHERE key = 'feed_scoring_weights';

  RETURN QUERY
  SELECT
    p.id, p.user_id, prof.username, prof.tier,
    CASE WHEN prof.total_games > 0 THEN ROUND((prof.total_wins::numeric / prof.total_games::numeric) * 100, 1) ELSE 0 END,
    prof.total_games, p.asset_symbol, p.timeframe, p.direction, p.target_percent, p.entry_price, p.status, p.profit,
    p.created_at, p.resolved_at, p.comment, p.likes_count,
    (
      (CASE WHEN p.status = 'WIN' THEN (v_weights->>'win_bonus')::numeric ELSE 0 END) + 
      (p.target_percent * (v_weights->>'target_weight')::numeric) + 
      (p.likes_count * (v_weights->>'like_weight')::numeric) +
      (CASE WHEN prof.total_games > 0 THEN (prof.total_wins::numeric / prof.total_games::numeric) * 100 * (v_weights->>'win_rate_weight')::numeric ELSE 0 END) -
      (EXTRACT(EPOCH FROM (NOW() - p.created_at)) / 3600 * (v_weights->>'time_decay')::numeric)
    )::numeric,
    p.is_opinion
  FROM predictions p
  JOIN profiles prof ON p.user_id = prof.id
  WHERE (p_asset_symbol IS NULL OR p.asset_symbol = p_asset_symbol) 
    AND (p_timeframe IS NULL OR p.timeframe = p_timeframe) 
    AND (p.comment IS NOT NULL AND length(p.comment) > 0) 
    AND (p.is_opinion = p_is_opinion)
  ORDER BY
    CASE WHEN p_sort_by = 'TOP' THEN 18 END DESC,
    CASE WHEN p_sort_by = 'NEW' THEN p.created_at END DESC,
    CASE WHEN p_sort_by = 'RISING' THEN (p.likes_count * 10 - (EXTRACT(EPOCH FROM (NOW() - p.created_at)) / 3600 * 5)) END DESC,
    p.created_at DESC
  LIMIT p_limit OFFSET p_offset;
END;
$$ LANGUAGE plpgsql STABLE;

-- 7. [RPC] resolve_prediction_advanced (System Configs + Audit + Stats + Notifications)
CREATE OR REPLACE FUNCTION public.resolve_prediction_advanced(
    p_id bigint,
    p_close_price numeric,
    p_open_price numeric DEFAULT NULL
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
declare
    v_prediction record;
    v_user_profile record;
    v_price_change numeric;
    v_price_change_percent numeric;
    v_status text;
    v_is_dir_correct BOOLEAN;
    v_is_target_hit BOOLEAN;
    
    -- Configs (from DB)
    v_house_edge NUMERIC;
    v_base_profit_ratio NUMERIC;
    v_tf_mults JSONB;
    v_target_bonuses JSONB;
    v_streak_mults JSONB;
    
    -- Calculation Variables
    v_tf_mult NUMERIC := 1.0;
    v_target_bonus INTEGER := 0;
    v_streak_mult NUMERIC := 1.0;
    v_profit_change INTEGER;
    v_payout INTEGER := 0;
    v_new_streak INTEGER;
    v_open_price NUMERIC;
    
    -- Notification vars
    v_notif_title TEXT;
    v_notif_msg TEXT;
begin
    -- 1. Get Prediction
    select * into v_prediction from predictions where id = p_id and status = 'pending' for update;
    if not found then return json_build_object('success', false, 'error', 'Already resolved'); end if;
    
    -- 2. Fetch System Configs
    SELECT (value->>0)::numeric INTO v_house_edge FROM system_configs WHERE key = 'house_edge';
    SELECT (value->>0)::numeric INTO v_base_profit_ratio FROM system_configs WHERE key = 'base_profit_ratio';
    SELECT value INTO v_tf_mults FROM system_configs WHERE key = 'tf_multipliers';
    SELECT value INTO v_target_bonuses FROM system_configs WHERE key = 'target_bonuses';
    SELECT value INTO v_streak_mults FROM system_configs WHERE key = 'streak_multipliers';
    
    v_open_price := COALESCE(p_open_price, v_prediction.entry_price);

    -- 3. Calculate Results
    v_price_change := p_close_price - v_open_price;
    IF v_open_price = 0 THEN v_price_change_percent := 0; ELSE v_price_change_percent := abs(v_price_change / v_open_price * 100); END IF;
    
    IF v_open_price = p_close_price THEN
        v_status := 'ND'; v_payout := v_prediction.bet_amount; v_profit_change := 0;
    ELSE
        -- Direction logic
        v_is_dir_correct := (v_prediction.direction = 'UP' AND v_price_change > 0) OR (v_prediction.direction = 'DOWN' AND v_price_change < 0);
        v_is_target_hit := (v_price_change_percent >= v_prediction.target_percent);

        IF v_is_dir_correct THEN
            v_status := 'WIN';
            -- Apply TF Multiplier from Config
            v_tf_mult := COALESCE((v_tf_mults->>v_prediction.timeframe)::numeric, 1.0);
            
            -- Apply Target Bonus from Config
            SELECT (val->>'bonus')::int INTO v_target_bonus 
            FROM jsonb_array_elements(v_target_bonuses) AS val 
            WHERE (val->>'max')::numeric >= v_prediction.target_percent 
            ORDER BY (val->>'max')::numeric ASC LIMIT 1;

            -- Update Streak
            IF v_is_target_hit THEN
                SELECT streak + 1 INTO v_new_streak FROM profiles WHERE id = v_prediction.user_id;
                v_streak_mult := COALESCE((v_streak_mults->>v_new_streak::text)::numeric, 1.0);
            ELSE
                v_new_streak := 0;
            END IF;

            -- Final Payout (Principal + (BaseProfit * Streak * HouseEdge))
            -- Direction Profit = Bet * Ratio * TF
            v_profit_change := ROUND((v_prediction.bet_amount * v_base_profit_ratio * v_tf_mult + v_target_bonus) * v_streak_mult * v_house_edge);
            v_payout := v_prediction.bet_amount + v_profit_change;
        ELSE
            v_status := 'LOSS'; v_payout := 0; v_profit_change := -v_prediction.bet_amount; v_new_streak := 0;
        END IF;
    END IF;
    
    -- 4. Update Tables
    update predictions set status = v_status, actual_price = p_close_price, entry_price = v_open_price, profit = v_profit_change, resolved_at = now() where id = p_id;
    update profiles set points = points + v_payout, total_games = total_games + 1, total_wins = total_wins + (CASE WHEN v_status = 'WIN' THEN 1 ELSE 0 END), streak = v_new_streak, total_earnings = total_earnings + v_profit_change where id = v_prediction.user_id;
    
    -- 5. Create Notification
    IF v_status = 'WIN' THEN v_notif_title := '✅ WIN: ' || v_prediction.asset_symbol; v_notif_msg := 'Earned ' || v_payout || ' pts.';
    ELSIF v_status = 'LOSS' THEN v_notif_title := '❌ LOSS: ' || v_prediction.asset_symbol; v_notif_msg := 'Missed target.';
    ELSE v_notif_title := 'Refund: No Change'; v_notif_msg := 'Stake returned.';
    END IF;

    INSERT INTO public.notifications (user_id, type, title, message, points_change, is_read) VALUES (v_prediction.user_id, 'prediction_resolved', v_notif_title, v_notif_msg, v_profit_change, FALSE);

    -- 6. Audit Log
    INSERT INTO activity_logs (user_id, action_type, asset_symbol, prediction_id, metadata)
    VALUES (v_prediction.user_id, 'RESOLVE', v_prediction.asset_symbol, p_id, json_build_object('status', v_status, 'profit', v_profit_change, 'payout', v_payout, 'streak', v_new_streak));
    
    return json_build_object('success', true, 'status', v_status, 'payout', v_payout, 'streak', v_new_streak);
exception when others then
    return json_build_object('success', false, 'error', SQLERRM);
end;
$$;
