-- Create a table for public profiles if it doesn't exist
create table if not exists public.profiles (
  id uuid not null references auth.users on delete cascade,
  email text,
  username text,
  points integer default 1000,
  tier text default 'bronze',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (id)
);

-- Turn on RLS (safe to run multiple times)
alter table public.profiles enable row level security;

-- Policies (Drop first to avoid errors if they exist)
drop policy if exists "Public profiles are viewable by everyone." on public.profiles;
create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

drop policy if exists "Users can insert their own profile." on public.profiles;
create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

drop policy if exists "Users can update own profile." on public.profiles;
create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, username, points)
  values (new.id, new.email, split_part(new.email, '@', 1), 1000)
  on conflict (id) do nothing; -- Handle case where profile already exists
  return new;
end;
$$ language plpgsql security definer;

-- Trigger: Drop first to avoid 'already exists' error
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Predictions Table
create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  asset_symbol text not null, -- e.g., 'BTCUSDT'
  direction text not null, -- 'UP' or 'DOWN'
  target_percent numeric not null, -- e.g., 0.5, 1.0
  entry_price numeric not null,
  status text default 'pending', -- 'pending', 'won', 'lost'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  resolved_at timestamp with time zone
);

alter table public.predictions enable row level security;

drop policy if exists "Predictions are viewable by everyone." on public.predictions;
create policy "Predictions are viewable by everyone." on public.predictions
  for select using (true);

drop policy if exists "Users can insert their own predictions." on public.predictions;
create policy "Users can insert their own predictions." on public.predictions
  for insert with check (auth.uid() = user_id);

-- Comments Table
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  asset_symbol text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.comments enable row level security;

drop policy if exists "Comments are viewable by everyone." on public.comments;
create policy "Comments are viewable by everyone." on public.comments
  for select using (true);

drop policy if exists "Users can insert their own comments." on public.comments;
create policy "Users can insert their own comments." on public.comments
  for insert with check (auth.uid() = user_id);
